### ISSUE TITLE
Errored

### ISSUE THREAD

**Issue by lightsourced** [jdsmith2816/khajiitearsshow#2]
With my modded setup when I run the synthesis patcher it errors out.

RecordException  => OpenGuardHelmKhajiitAA (001003:Open Face Guard Helmets.esp<ArmorAddon>): BODT type not expected on versions >= 44 System.ArgumentException: BODT type not expected on versions >= 44
   at Mutagen.Bethesda.Skyrim.Internals.BodyTemplateBinaryOverlay.CustomFactory(OverlayStream stream, BinaryOverlayFactoryPackage package)
   at Mutagen.Bethesda.Skyrim.Internals.ArmorAddonBinaryOverlay.GetBodyTemplateCustom()
   at Mutagen.Bethesda.Skyrim.Internals.ArmorAddonBinaryOverlay.get_BodyTemplate()
   at KhajiitEarsShow.Program.RunPatch(IPatcherState`2 state) in C:\Users\user\AppData\Local\Temp\Synthesis\3fe25fae-f7a3-4606-815a-da1b532abbc1\Git\s4t14yst.xhi\Runner\KhajiitEarsShow\Program.cs:line 40   at KhajiitEarsShow.Program.RunPatch(IPatcherState`2 state) in C:\Users\jesso\AppData\Local\Temp\Synthesis\3fe25fae-f7a3-4606-815a-da1b532abbc1\Git\s4t14yst.xhi\Runner\KhajiitEarsShow\Program.cs:line 49
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 93
--- End of stack trace from previous location ---

**Comment by TwistedModding** [comment]
something seems to be wrong with: 001003, check that record in xedit

**Comment by Noggog** [comment]
This isn't related to this patcher specifically, and is more related to Mutagen being unhappy with a record that says it's FormVersion 44, and should have newer context, but still has formats from versions 43 or earlier.   Try to take a look at the specific record and either fully upgrade it to FormVersion 44, or downgrade it.   Mutagen might get more relaxed on this topic in the future, but for now it's something you have to handle yourself.
